on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 18 * * *'

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - name: Get JSON
        id: get_json
        run: 'curl --silent https://www.wta.org/volunteer/schedule/workparties.json\?regions\=Central%20Cascades\&regions\=Issaquah%20Alps\&regions\=North%20Cascades\&regions\=Puget%20Sound%20and%20Islands\&regions\=Snoqualmie%20Region\&batch_size\=10\&tab\=map\&days\=Weekends\&includeWaitlisted\=true\&date\=In%20the%20future\&includeCompleted\=false'
      - name: Get all event IDs
        uses: sergeysova/jq-action@v2
        id: get-all-event-ids
        with:
          cmd: echo "${{ steps.get_json.outputs.value }}" | jq ".results.all_items | map(._id) | sort | join(',')"
