on:
  push:
    branches:
      - main
  # Run at the end of each day (Pacific Time)
  schedule:
    - cron: '0 10 * * *'

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - name: Get last run's event IDs
        uses: dawidd6/action-download-artifact@v2
        with:
          # Only use `main`-branch workflow runs; might be a pain
          # in the future
          branch: main
          # Only use workflows that have an artifact with this step's
          # `name` value
          search_artifacts: true
          name: all-event-ids.txt
          # Store this previous run's file in the `cache` directory
          path: cache
      - name: Get event IDs
        uses: sergeysova/jq-action@v2
        with:
          # The cURL'd URL is currently filtered down to:
          # - Seattle region
          # - weekend
          cmd: curl --silent https://www.wta.org/volunteer/schedule/workparties.json\?regions\=Central%20Cascades\&regions\=Issaquah%20Alps\&regions\=North%20Cascades\&regions\=Puget%20Sound%20and%20Islands\&regions\=Snoqualmie%20Region\&batch_size\=10\&tab\=map\&days\=Weekends\&includeWaitlisted\=true\&date\=In%20the%20future\&includeCompleted\=false | jq --raw-output ".results.all_items | map(._id) | sort | .[]" > all-event-ids.txt
      - name: Cache event IDs
        uses: actions/upload-artifact@v3
        with:
          name: all-event-ids.txt
          path: all-event-ids.txt
      - name: Detect new event IDs and format
        id: new_events
        # Use `--changed-group-format` to prepend the base URL to
        # each of the new event IDs, and use `xargs` to switch from
        # newline delimiting to space delimiting
        run: diff --changed-group-format='https://www.wta.org/volunteer/schedule/workparty/%<' --unchanged-group-format='' all-event-ids.txt cache/all-event-ids.txt | xargs
      - name: Text if have found new events
        if: steps.new_events.outputs.value != ''
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: ${{ secrets.FROM_PHONE_NUMBER }}
          toPhoneNumber: ${{ secrets.TO_PHONE_NUMBER }}
          message: 'New WTA events found: ${{ steps.new_events.outputs.value }}'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
      # This step can probably be scrapped once I'm confident that
      # the system is working correctly
      - name: Text if have found no new events
        if: steps.new_events.outputs.value == ''
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: ${{ secrets.FROM_PHONE_NUMBER }}
          toPhoneNumber: ${{ secrets.TO_PHONE_NUMBER }}
          message: 'No new WTA events found'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
